vmp("enable"), vmp("smooth"), vmp("max_angle_in_degrees"),
    vmp("divide_angle_by_distance"), vmp("hold_target"),
    vmp("check_for_obstacles"), vmp("check_for_distance"),
    vmp("ignore_the_dead"), vmp("ignore_same_group"),
    vmp("ignore_friendly_nicknames"), vmp("ignore_same_color"),
    vmp("aim_only_when_shooting"), vmp("head"), vmp("neck"),
    vmp("right_shoulder"), vmp("left_shoulder"), vmp("right_elbow"),
    vmp("left_elbow"), vmp("stomach"), vmp("right_knee"), vmp("left_knee"),
    vmp("model_groups"), vmp("friendly_nicknames"), vmp("min_distance"),
    vmp("delay_between_target_changes"), vmp("do_not_change_z_angle")